spring:
  application:
    name: muroba
  output:
    ansi:
      enabled: always
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MUROBA_DB?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: mysql1010
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/muroba
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.orm.jdbc.bind: trace
      root: info
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
#   ${MAIL_USERNAME}처럼 환경변수로 가져오기
    username: 
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000